### ISSUE TITLE
Erros on newer singularity version (>= 3.7.4)

### ISSUE THREAD

**Issue by AMarinhoSN** [dezordi/IAM_SARSCOV2#1]
I keep getting the errors below when running the container on singularity version > 3.7.1 using the README instructions. 

## The errors

First error occurs due to SIF have no writable partition

```{bash}
FATAL:   no SIF writable overlay partition found in /HDD/Projects/module_2_dev/backend_box/ROUTINES/IAM_SARSCOV2/iam_sarscov2_container
```
Adding the --writable-tmpfs flag at the singularity line at 'sars2_assembly_singularity_run.sh' solves this. But the pipeline fails to start the conda environment, it does not recognize the python command and I got this error:

```{bash}
Activating conda via bash
Activating pangolin
/home/amarihosn/sars2_assembly_singularity: line 70: conda: command not found


/home/amarihosn/sars2_assembly_singularity: line 94: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 105: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 116: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 117: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 128: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 139: python: command not found
/home/amarihosn/sars2_assembly_singularity: line 150: python: command not found
```
-----

## The reasons

Given that versions >= 3.7.4 include [important security fixes](https://github.com/sylabs/singularity/releases/tag/v3.7.4), is mandatory to run this or newer versions, especially if you plan to run it on HPC environments.

After a little digging using the singularity shell command, I notice that the /root/ directory on the container just points to my local home directory (I could even delete some files from there). The pipeline expects miniconda files at /root/ and fails because there is no miniconda there. 

------

## The fix

For some reason, everything works fine if you **build the image as a sandbox instead of a SIF file**.  Just run:

```{bash}
 singularity build --fakeroot --sandbox IAM_SARSCOV2_container Singularityfile 
```

This will generate a directory with all container dir and files. You can check the /root/ and see that the miniconda files are there.
I don't know why this happens, but it seems to be related to the way SIF files handle the dir structure and I have no idea how to fix this.
Also, I am not sure if this is a general issue or something specific to my system, but this workaround works just fine here. I decided to add this issue in the hopes to save some hours of pain from other people facing the same errors.

**Comment by dezordi** [comment]
Thanks @AMarinhoSN I updated the Readme with the instructions that you informed me.

Best,

Filipe

**Comment by AMarinhoSN** [comment]
Now I am a collaborator and I have the power to close this issue >D.
Behold my power!
