### ISSUE TITLE
Compiling outputs issue 

### ISSUE THREAD

**Issue by AndreaAguadoM** [dezordi/IAM_SARSCOV2#11]
Hello. 
After running ViralFlow using docker, I got as output different files (as described in wiki) within a created directory. Right now I am trying to compile the different obtained outputs using the following line: 

viralflow --compileOutput -inputDir ./ViralFlow_outputs_directory/ -outDir ./new_directory

But I obtain the following output message: 

@ compiling output files
  > Total 0 samples processed
ERROR: No ViralFlow output files found

**Comment by dezordi** [comment]
Hello Andrea, could you run the command 'ls' on  './ViralFlow_outputs_directory/' and paste here the output?

**Comment by AndreaAguadoM** [comment]
Hello, I finally solved this problem. It was because I was trying to run this code within the results directory, when I had to do it from the previous directory. Thanks!!
