### ISSUE TITLE
insertsize.plot

### ISSUE THREAD

**Issue by AndreaAguadoM** [dezordi/IAM_SARSCOV2#12]
Hello! 
After running ViralFlow, one of the obtained files is the insertsize.plot, which has the following shape: 

0	0	0.000000	112696	1.000000
1	0	0.000000	112696	1.000000
2	0	0.000000	112696	1.000000
3	0	0.000000	112696	1.000000
4	0	0.000000	112696	1.000000
5	0	0.000000	112696	1.000000
6	0	0.000000	112696	1.000000

I was wondering what does every column relies on, what information are they giving to the user about the results. Without the column labels it gets a little bit difficult. It happens the same with the depth_distribution.plot output file. 

Thanks in advance!

**Comment by dezordi** [comment]
> Hello! After running ViralFlow, one of the obtained files is the insertsize.plot, which has the following shape:
> 
> 0 0 0.000000 112696 1.000000 1 0 0.000000 112696 1.000000 2 0 0.000000 112696 1.000000 3 0 0.000000 112696 1.000000 4 0 0.000000 112696 1.000000 5 0 0.000000 112696 1.000000 6 0 0.000000 112696 1.000000
> 
> I was wondering what does every column relies on, what information are they giving to the user about the results. Without the column labels it gets a little bit difficult. It happens the same with the depth_distribution.plot output file.
> 
> Thanks in advance!

Hello Andrea, these files are default outputs of bamdst tool. In fact, the authors of bamdst don't explain the mean of each column value. The unique explanation that we have about the insertsize.plot (the bamdst documentation doesn't cite the depth_distribuition.plot) files, based on bamdst documentation is: distribution data of inferred insert size
