### ISSUE TITLE
RROR: referenceGenome provided is not a file.

### ISSUE THREAD

**Issue by nityendra21** [dezordi/IAM_SARSCOV2#13]
Hello, I am getting the following error when trying to run ViralFlow:
`ERROR: referenceGenome provided (/home/myname//viralflow_test/home/myname/Softwares/ViralFlow/test_files/reference.fasta) is not a file.`
My input is: 
`viralflow --run -inputDir /home/myname/viralflow_test -referenceGenome /home/myname/Softwares/ViralFlow/test_files/reference.fasta -adaptersFile /home/myname/viralflow_test/adapters.txt -totalCpus 2 -depth 5 -minLen 35 -outDir /home/myname/viralflow_test/viralflow ` and I've installed the software following the pip method. 

Thanks in advance!

**Comment by dezordi** [comment]
> Hello, I am getting the following error when trying to run ViralFlow: `ERROR: referenceGenome provided (/home/myname//viralflow_test/home/myname/Softwares/ViralFlow/test_files/reference.fasta) is not a file.` My input is: `viralflow --run -inputDir /home/myname/viralflow_test -referenceGenome /home/myname/Softwares/ViralFlow/test_files/reference.fasta -adaptersFile /home/myname/viralflow_test/adapters.txt -totalCpus 2 -depth 5 -minLen 35 -outDir /home/myname/viralflow_test/viralflow ` and I've installed the software following the pip method.
> 
> Thanks in advance!

Hello nityendra21,  test as:

`viralflow --run -inputDir /home/myname/viralflow_test -referenceGenome reference.fasta -adaptersFile adapters.txt -totalCpus 2 -depth 5 -minLen 35 -outDir /home/myname/viralflow_test/viralflow`

Considering that reference.fasta and adapters.txt are stored in /home/myname/viralflow_test/ you don't pass the entire path in the specific arguments -referenceGenome and -adaptersFile

**Comment by nityendra21** [comment]
That worked, thank you!
