### ISSUE TITLE
Problemas na instalação via git + conda + pip 

### ISSUE THREAD

**Issue by grazLet** [dezordi/IAM_SARSCOV2#14]
Olá, bom dia! 

Estou tentando realizar a instalação local do viralflow no Ubuntu 20.04 via pip. Entretanto, não obtive sucesso porque após a instalaçao via pip vem apenas os programas viralflow_dev  virtualenv são instalados no ambiente do conda. 

![Screenshot_20221005_090923](https://user-images.githubusercontent.com/46760546/194057035-1fe8a0ff-0f78-43d2-874f-3588a28891ae.png)

**Comment by dezordi** [comment]
Olá @grazLet , uma dúvida, você tentou instalar a versão do branch em desenvolvimento? pois o `viralflow_dev` é o executável da versão em desenvolvimento, e ainda não está pronta para testes.

No seu problema especiífico, após executar as linhas:
```
git clone https://github.com/dezordi/ViralFlow.git
cd ViralFlow/
conda env create -f envs/viralflow.yml
conda activate viralflow
pip install -e ./
```
e
```
viralflow --help
``` 

É informada a mensagem de help da ferramenta, ou uma mensagem do S.O. informando que a ferramenta não existe?

Caso após seguir os passos acimas o erro persista, tente remover o `viralflow_dev`  com pip, utilizando:
```
pip uninstall viralflow_dev
```
Repita as linhas para instalação da versão 0.6.0 do ViralFlow, e se o problema persistir, nos informe.

Att.

**Comment by grazLet** [comment]
> Olá @grazLet , uma dúvida, você tentou instalar a versão do branch em desenvolvimento? pois o `viralflow_dev` é o executável da versão em desenvolvimento, e ainda não está pronta para testes.
> 
> No seu problema especiífico, após executar as linhas:
> 
> ```
> git clone https://github.com/dezordi/ViralFlow.git
> cd ViralFlow/
> conda env create -f envs/viralflow.yml
> conda activate viralflow
> pip install -e ./
> ```
> 
> e
> 
> ```
> viralflow --help
> ```
> 
> É informada a mensagem de help da ferramenta, ou uma mensagem do S.O. informando que a ferramenta não existe?
> 
> Caso após seguir os passos acimas o erro persista, tente remover o `viralflow_dev` com pip, utilizando:
> 
> ```
> pip uninstall viralflow_dev
> ```
> 
> Repita as linhas para instalação da versão 0.6.0 do ViralFlow, e se o problema persistir, nos informe.
> 
> Att.

olá, muito obrigada pelo retorno!

**Comment by dezordi** [comment]
@grazLet isso foi resolvido?

**Comment by grazLet** [comment]
> @grazLet isso foi resolvido?

sim, foi resolvido! Não consegui desinstalar utilizando o pip, porém consegui remover os executáveis do viralflow_dev. Obrigada!
