### ISSUE TITLE
Erros no pangolin utilizando os arquivos de teste na versão local do viralflow

### ISSUE THREAD

**Issue by grazLet** [dezordi/IAM_SARSCOV2#15]
Olá, estou utilizando o viralflow na versão local e testando com os arquivos da pasta test_files. 

minha linha de comando é esta: 
viralflow --run -inputDir test_files/ \
                -referenceGenome reference.fasta \
                -adaptersFile ART_adapters.fa -totalCpus 4 -depth 5 \
                -minLen 75 -minDpIntrahost 100 -trimLen 0 \
                -nxtBin /home/lacen/documentos/dependencias/nextclade/nextclade \
                -nxtDtset /home/lacen/documentos/dependencias/nextclade/dataset/sars-cov-2 -v

O primeiro erro é o 
_@ Naming variants identified..._
_Error in PANGOLIN, check log file (test_files/Cneg.results/Cneg_4_pangolin)_
 _> total execution time :  9.72627592086792_

E o segundo 
_>--- STEP 4 ---<_
_@ Naming variants identified..._
_Error in PANGOLIN, check log file (test_files/ART2.results/ART2_4_pangolin)_
_Error in PANGOLIN, check log file (test_files/ART1.results/ART1_4_pangolin)_

Adicionei os arquivos de log com os erros. Desde já muito obrigada. 

[Cneg_4_pangolin_err.log](https://github.com/dezordi/ViralFlow/files/9734808/Cneg_4_pangolin_err.log)
[ART2_4_pangolin_err.log](https://github.com/dezordi/ViralFlow/files/9734809/ART2_4_pangolin_err.log)
[ART1_4_pangolin_err.log](https://github.com/dezordi/ViralFlow/files/9734814/ART1_4_pangolin_err.log)

**Comment by dezordi** [comment]
Boa noite,

O erro está ocorrendo nesta função, antes de chamar o pangolin
https://github.com/dezordi/ViralFlow/blob/main/viralflow/calls.py#L341-L404

Por algum motivo, o `_4` está sendo incluso no nome da amostra. @AMarinhoSN sabe o que pode estar ocorrendo?

**Comment by dezordi** [comment]
Olá, você pode testar implementando a versão v0.1.0 ?

**Comment by dezordi** [comment]
Solved on https://github.com/dezordi/ViralFlow/pull/40
