### ISSUE TITLE
/bin/bash: /home/pango_update: No such file or directory no comando viralflow --build -containerService docker

### ISSUE THREAD

**Issue by grazLet** [dezordi/IAM_SARSCOV2#16]
Olá, estou tentando utilizar a ferramenta pelo Docker, mas recebo o seguinte erro: 

_**/bin/bash: /home/pango_update: No such file or directory**_

Olhando o arquivo Dockerfile percebi que na linha 12 o comando RUN /bin/bash -c "source /home/pango_update" busca pelo arquivo  pango_update que realmente não está na path /home/pango_update, mas sim na path ~/ViralFlow (pasta que vem com o git clone).
Quando eu chamo o comando _**source /home/lacen/ViralFlow/pango_update**_ ele consegue ativar o ambiente do pangolin e logo em seguida realizar as atualizações. 

_$ source /home/lacen/ViralFlow/pango_update 
Activating pangolin
Updating pangolin
pangolin already latest release (v4.1.2)
pangolin-data already latest release (v1.14)
constellations already latest release (v0.1.10)
scorpio already latest release (v0.3.17)_

Saberia me dizer como eu posso resolver este problema?

**Comment by dezordi** [comment]
Olá, você pode testar implementando a versão v0.1.0 ?

**Comment by dezordi** [comment]
Solved on https://github.com/dezordi/ViralFlow/pull/40

**Comment by dezordi** [comment]
Solved on https://github.com/dezordi/ViralFlow/pull/40
