### ISSUE TITLE
Erro na rodada teste

### ISSUE THREAD

**Issue by kayobianco** [dezordi/IAM_SARSCOV2#35]
Pessoal, tudo bem?

Instalei o Viralflow e estou tentando rodar o teste, mas sem sucesso. Segue o log:

(viralflow) kayobianco@:~/ViralFlow$ viralflow -run --params_file test_files/sars-cov-2.params
ViralFlow v0.1.0
NXF_VER=22.04.0 nextflow run /home/kayobianco/ViralFlow//vfnext/main.nf --virus sars-cov2 --outDir /home/kayobianco/ViralFlow/test_files/sars-cov-2/outputs --inDir /home/kayobianco/ViralFlow/test_files/sars-cov-2/input --runSnpEff true --writeMappedReads true --minLen 75 --depth 25 --minDpIntrahost 100 --trimLen 0 --fastp_threads 1 --bwa_threads 1 --mafft_threads 1 -resume
N E X T F L O W  ~  version 22.04.0
Launching `/home/kayobianco/ViralFlow/vfnext/main.nf` [deadly_noether] DSL2 - revision: 72092b7946

===========================================
VFNEXT v0.1.0
parameters:
-------------------------------------------
--inDir            : /home/kayobianco/ViralFlow/test_files/sars-cov-2/input
--outDir           : /home/kayobianco/ViralFlow/test_files/sars-cov-2/outputs
--virus            : sars-cov2
--refGenomeCode   *: null
--referenceGenome *: null
--referenceGFF    *: null
--primersBED       : null
--minLen           : 75
--depth            : 25
--minDpIntrahost   : 100
--trimLen          : 0
--databaseDir      : /home/kayobianco/ViralFlow/vfnext/databases/
--runSnpEff        : true
--writeMappedReads : true
--nextflowSimCalls : null
--fastp_threads    : 1
--bwa_threads      : 1
--mafft_threads    : 1
--mapping_quality  : 30
--base_quality     : 30
--minBamSize       : 500

* Only required for "custom" virus
Runtime data:
-------------------------------------------
Running with profile:   standard
Run container:          [:]
Running as user:        kayobianco
Launch dir:             /home/kayobianco/ViralFlow
Base dir:               /home/kayobianco/ViralFlow/vfnext
------------------------------------------

WARN: An BED file with primer positions was not provided. The pipeline will not run samtools clip to remove primer regions
WARN: Number of requested simultaneous nextflow calls (null) was set to max cpus available (8)
executor >  local (4)
[ee/d272fc] process > processInputs:prepareDatabase [  0%] 0 of 1
[-        ] process > indexReferenceBWA             -
[-        ] process > genFaIdx                      -
[17/280151] process > runFastp (3)                  [  0%] 0 of 3
[-        ] process > align2ref                     -
[-        ] process > getMappedReads                -
[-        ] process > getUnmappedReads              -
[-        ] process > bamToFastq                    -
[-        ] process > runIvar                       -
[-        ] process > runReadCounts                 -
[f9/ac819c] process > checkSnpEffDB                 [100%] 1 of 1, cached: 1 ✔
[-        ] process > runSnpEff                     -
[-        ] process > runVfReport                   -
[-        ] process > alignConsensus2Ref            -
[-        ] process > runPicard                     -
[-        ] process > fixWGS                        -
[-        ] process > runIntraHostScript            -
[-        ] process > runPangolin                   -
[-        ] process > runNextClade                  -
[-        ] process > compileOutputs_SC2            -
Error executing process > 'processInputs:prepareDatabase'

Caused by:
  Process `processInputs:prepareDatabase` terminated with an error exit status (127)

Command executed:

  # download fasta from NCBI
  esearch -db nucleotide -query NC_045512.2              | efetch -format fasta > NC_045512.2.fa
  # download gff from NCBI
  wget -O NC_045512.2.gff            "https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?db=nuccore&report=gff3&id=NC_045512.2"

Command exit status:
  127
executor >  local (4)
[ee/d272fc] process > processInputs:prepareDatabase [100%] 1 of 1, failed: 1 ✘
[-        ] process > indexReferenceBWA             -
[-        ] process > genFaIdx                      -
[-        ] process > runFastp (3)                  -
[-        ] process > align2ref                     -
[-        ] process > getMappedReads                -
[-        ] process > getUnmappedReads              -
[-        ] process > bamToFastq                    -
[-        ] process > runIvar                       -
[-        ] process > runReadCounts                 -
[f9/ac819c] process > checkSnpEffDB                 [100%] 1 of 1, cached: 1 ✔
[-        ] process > runSnpEff                     -
[-        ] process > runVfReport                   -
[-        ] process > alignConsensus2Ref            -
[-        ] process > runPicard                     -
[-        ] process > fixWGS                        -
[-        ] process > runIntraHostScript            -
[-        ] process > runPangolin                   -
[-        ] process > runNextClade                  -
[-        ] process > compileOutputs_SC2            -
Error executing process > 'processInputs:prepareDatabase'

Caused by:
  Process `processInputs:prepareDatabase` terminated with an error exit status (127)

Command executed:

  # download fasta from NCBI
  esearch -db nucleotide -query NC_045512.2              | efetch -format fasta > NC_045512.2.fa
  # download gff from NCBI
  wget -O NC_045512.2.gff            "https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?db=nuccore&report=gff3&id=NC_045512.2"

Command exit status:
  127

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
  .command.sh: line 3: esearch: command not found
  .command.sh: line 3: efetch: command not found

Work dir:
  /home/kayobianco/ViralFlow/work/ee/d272fc7347ea6d851d97e45a2267ea

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Podem ajudar?

**Comment by costahud** [comment]
Thanks for reporting this error, @kayobianco. The fix was provided (https://github.com/dezordi/ViralFlow/pull/40)  and was solved on version 1.0.0.
